keys:
  - &john age1wucy7a4hwxwsyuk6uj86ctxyuqatmxykk20t5dl3lf3g2fmtwpzslnv9s2
  - &rock5c age1rk9rlvtsjpwrwgktf6fjwljz0vy64l5kv5z5p493wr77w3ry09nsgdvffp
creation_rules:
  - path_regex: nixos-configurations/rock5c_minimal/secrets\.yaml$
    key_groups:
      - age:
        - *rock5c
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *john
