# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  options,
  modulesPath,
  inputs,
  ...
}:
{
  imports = [
    inputs.nixos-hardware.nixosModules.framework-11th-gen-intel
  ];

  dev.johnrinehart.droidcam.enable = false; # TODO: broken

  nix.settings = {
    extra-experimental-features = "nix-command flakes";
    trusted-users = [ "john" ];
  };

  boot.supportedFilesystems = [
    "ntfs"
    "exfat"
    "vfat"
    "btrfs"
    "ext"
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "uas"
    "usb_storage"
    "sd_mod"
  ];

  boot.initrd.kernelModules = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/9dbd56c9-2344-450a-845b-6490d0879256";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/32F9-A71A";
    fsType = "vfat";
  };

  fileSystems."/mnt/framework250_1" = {
    device = "/dev/disk/by-uuid/caca60c2-483b-4a58-a443-5c8df3b3c82d";
    fsType = "btrfs";
    options = [
      "user"
      "rw"
      "async"
      "auto"
      "nofail"
      "x-systemd.device-timeout=2s"
    ];
  };

  # The global useDHCP flag is deprecated, therefore explicitly set to false here.
  # Per-interface useDHCP will be mandatory in the future, so this generated config
  # replicates the default behaviour.
  networking.hostName = "framie";
  networking.useDHCP = lib.mkDefault false;
  networking.nameservers = [
    "1.1.1.1"
    "8.8.8.8"
    "6.6.6.6"
  ];
  networking.resolvconf.enable = true;
  networking.interfaces.wlp170s0.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.enableRedistributableFirmware = true;

  security.rtkit.enable = true;

  # bluetooth stuff
  services.blueman.enable = true;
  hardware = {
    bluetooth.enable = true;
  };

  ## Below v4l2loopback stuff stolen from https://gist.github.com/TheSirC/93130f70cc280cdcdff89faf8d4e98ab
  # Extra kernel modules
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.extraModulePackages = [ config.boot.kernelPackages.v4l2loopback ];

  environment.etc."modprobe.d/v4l2loopback.conf".text = ''
    options v4l2loopback video_nr=0,1,2 card_label="Virtual Video 0,Virtual Video 1,Virtual Video 2" exclusive_caps=1
  '';

  environment.etc."modules-load.d/v4l2loopback.conf".text = ''
    v4l2loopback
  '';

  boot.kernelModules = [
    "kvm-intel" # detected automatically
  ];

  services.chrony = {
    enable = true;
    # if we're off by >1s then jump system clock only within the 1st 3 clock
    # updates
    extraConfig = ''
      makestep 1 3
    '';
  };

  services.tailscale.enable = true;
  networking.firewall.checkReversePath = "loose";

  # Fix tailscaled hanging during shutdown when trying to cleanup UPnP port mappings
  # The daemon has an internal 45s watchdog timeout when closing, which blocks shutdown.
  # It tries to delete port mappings from the router, but this hangs if the network
  # is going down or the router is unresponsive.
  systemd.services.tailscaled = {
    # Stop tailscale BEFORE network goes down during shutdown
    # Only use network.target to avoid ordering cycles with NetworkManager
    before = [ "network.target" ];

    serviceConfig = {
      # Gracefully disconnect from tailnet before stopping the daemon
      # This avoids hanging on UPnP port mapping cleanup during shutdown
      ExecStop = "${pkgs.tailscale}/bin/tailscale down --accept-risk=all";

      # Still set a timeout as a safety measure
      # Should complete quickly now that we disconnect first
      TimeoutStopSec = "2s";

      # Send SIGTERM first, then SIGKILL after timeout
      KillMode = "process";
    };
  };

  networking.timeServers = options.networking.timeServers.default ++ [ "time.facebook.com" ];

  programs.noisetorch.enable = true;

  networking.networkmanager.enable = true;
  systemd.services.NetworkManager-wait-online.enable = false;

  services.upower = {
    enable = true;
  };
}
