{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.dev.johnrinehart.desktop.wl-hyprland;
  hyprlandSessionInit = pkgs.writeShellScript "rock5c-hyprland-session-init" ''
    set -eu

    export XDG_CURRENT_DESKTOP=Hyprland
    export XDG_SESSION_TYPE=wayland

    ${lib.getExe' pkgs.dbus "dbus-update-activation-environment"} --systemd \
      DISPLAY \
      WAYLAND_DISPLAY \
      XDG_CURRENT_DESKTOP \
      XDG_SESSION_DESKTOP \
      XDG_SESSION_TYPE \
      XDG_RUNTIME_DIR \
      HYPRLAND_INSTANCE_SIGNATURE \
      QT_QPA_PLATFORM \
      NIXOS_OZONE_WL || true

    systemctl --user start graphical-session.target || true
    systemctl --user start rock5c-kodi-autostart.service || true
  '';
in
{
  options.dev.johnrinehart.desktop.wl-hyprland = {
    enable = lib.mkEnableOption "the Wayland with Hyprland configuration.";
  }
  // {
    default = false;
  };

  config = lib.mkIf cfg.enable {
    environment.sessionVariables = {
      NIXOS_OZONE_WL = "1";
    };

    programs.hyprland.enable = true;
    environment.etc."xdg/hypr/hyprland.conf".text = ''
      # Provide a real system Hyprland config so greetd sessions do not fall back
      # to Hyprland's autogenerated empty config warning.
      exec-once = ${hyprlandSessionInit}
    '';

    users.users.john.extraGroups = [ "seat" ];

    services.greetd.enable = true;
    services.greetd.settings.default_session = {
      command = "${lib.getExe config.programs.hyprland.package}";
      user = "john";
    };
  };
}
