diff --git a/drivers/gpu/arm/bifrost/csf/Kbuild b/drivers/gpu/arm/bifrost/csf/Kbuild
index 8159bc9d10e8..0bda706bd53b 100644
--- a/drivers/gpu/arm/bifrost/csf/Kbuild
+++ b/drivers/gpu/arm/bifrost/csf/Kbuild
@@ -50,6 +50,7 @@ ifeq ($(CONFIG_MALI_BIFROST_NO_MALI),y)
 bifrost_kbase-y += csf/mali_kbase_csf_firmware_no_mali.o
 bifrost_kbase-y += csf/mali_kbase_csf_fw_io_no_mali.o
 else
+ccflags-y := -I$(srctree)
 bifrost_kbase-y += csf/mali_kbase_csf_firmware.o
 bifrost_kbase-y += csf/mali_kbase_csf_fw_io.o
 endif
