name: "John OS builder :)"
# description: "Build John OS from the system flake :)"
on:
  schedule:
    - cron: "0 0 1/14 * *" # At 12:00 AM, every 14 days, starting at month beginning
  push:
    tags:
      - 'v*'
jobs:
  builds:
    name: "nix build and release flow"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2.4.0
      with:
        fetch-depth: 0 # nix flakes do not work on shallow clones

    - name: Install Nix (Cachix)
      uses: cachix/install-nix-action@74ef8ad2cfb373eef5eb62483d242712e1e1ac07
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/grmc0pws5zskk5qshq9vnd77y0gb6whk/install
        install_options: --tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve

    - name: Setup Build Environment
      run: |
        # free up disk space in the runner
        # cf., https://github.com/actions/virtual-environments/issues/2606#issuecomment-772683150
        df -lh # before cleaning up
        sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
        sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
        df -lh # after cleaning up
        sudo apt update && sudo apt install tree && tree -l -L 3 # for checking the build directory, later

    - name: Build JohnOS 🔨🔨🔨
      run: |
        nix build .#flash-drive-iso
        split ./result/iso/*.iso ./johnOS-${GITHUB_SHA}.iso. -d -b $((2*(1<<30)-1))
        df -lh

    - name: Release 🚀🚀🚀
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./johnOS-*.iso*
