name: "John OS builder :)"
# description: "Build John OS from the system flake :)"
on:
  push:
    tags:
      - 'v*'
jobs:
  builds:
    name: "nix build and release flow"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2.4.0
      with:
        fetch-depth: 0 # nix flakes do not work on shallow clones

    - name: Install Nix (Cachix)
      uses: cachix/install-nix-action@v16

    - name: Setup Build Environment
      run: |
        # free up disk space in the runner
        # cf., https://github.com/actions/virtual-environments/issues/2606#issuecomment-772683150
        df -lh # before cleaning up
        sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
        sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
        df -lh # after cleaning up

    - name: Build JohnOS 🔨🔨🔨
      run: |
        nix build .#flash-drive-iso
        split ./result/iso/*.iso ./johnOS-${GITHUB_SHA}.iso. -d -b $((2*(1<<30)-(1<<8)))
        df -lh # check how much space compared to before

    - name: Release 🚀🚀🚀
      uses: softprops/action-gh-release@v0.1.14
      with:
        generate_release_notes: true
        files: |
          ./johnOS-*.iso*
