name: "JohnOS Builder 👷"
on:
  push:
    tags:
      - 'v*'
jobs:
  builds:
    name: "nix build and release flow"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2.4.0
      with:
        path: repo # checkout repo to $GITHUB_WORKSPACE/repo
        fetch-depth: 0 # nix flakes do not work on shallow clones

    - name: Install Nix (Cachix)
      uses: cachix/install-nix-action@v16

    - name: Setup Build Environment
      run: |
        # free up disk space in the runner
        # cf., https://github.com/actions/virtual-environments/issues/2606#issuecomment-772683150
        df -lh # before cleaning up
        sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
        sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
        df -lh # after cleaning up

    - name: Build JohnOS 🔨🔨🔨
      run: |
        tree -l -L 8 ${{ github.workspace }}
        ${{ github.workspace }}/repo/.github/build_and_split.sh
        tree -l -L 8 ${{ github.workspace }}
        df -lh # check how much space compared to before

    - name: Release 🚀🚀🚀
      uses: softprops/action-gh-release@v0.1.14
      with:
        generate_release_notes: true
        files: |
          ${{ github.workspace }}/split/*
